# Generated by Django 5.2 on 2025-05-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, default='profile_image/Screenshot_2023-11-17_003842.png', upload_to='profile_image'),
        ),
    ]
