# Generated by Django 5.2 on 2025-04-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskdetail_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskDetail',
        ),
    ]
