# Generated by Django 5.2 on 2025-05-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_assign_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
