# Generated by Django 5.2 on 2025-05-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_delete_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetail',
            name='assign_to',
        ),
        migrations.AddField(
            model_name='taskdetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='task_details'),
        ),
    ]
