# Generated by Django 5.2 on 2025-05-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_taskdetail_assign_to_taskdetail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='image',
            field=models.ImageField(blank=True, default='task_details/download.png', null=True, upload_to='task_details'),
        ),
    ]
