# Generated by Django 5.2 on 2025-04-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_taskdetail_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assign_to',
            field=models.ManyToManyField(related_name='tasks', to='tasks.employee'),
        ),
    ]
