# Generated by Django 5.2 on 2025-04-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_assign_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assign_to',
            field=models.ManyToManyField(to='tasks.employee'),
        ),
    ]
